exports.languages = {
  id: "Bahasa Indonesia",
  da: "Dansk",
  de: "Deutsch",
  en: "English",
  et: "Eesti",
  es: "Español",
  fr: "Français",
  it: "Italiano",
  lt: "Lietuvių",
  lv: "Latviešu",
  hu: "Magyar",
  nl: "Nederlands",
  nb: "Norsk bokmål",
  pl: "Polski",
  pt: "Português",
  "pt-BR": "Português do Brasil",
  ro: "Română",
  sk: "Slovenčina",
  sl: "Slovenščina",
  fi: "Suomi",
  sv: "Svenska",
  tr: "Türkçe",
  cs: "Česky",
  bg: "Български",
  el: "Ελληνικά",
  ru: "Русский",
  uk: "Українська",
  ar: "العربية",
  hi: "हिन्दी",
  ja: "日本語",
  ko: "한국어",
  vi: "Tiếng Việt",
  "zh-CN": "简体中文",
  fa: "فارسی",
  he: "עברית",
  th: "ไทย"
};

exports.defaultLanguage = "en";